import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
import cors from "cors";
import { z } from "zod";
import { db } from "../db/index.js";
import { artifacts, feedback } from "../db/schema.js";
import { eq, desc, ilike, or, sql } from "drizzle-orm";
import { summarizeFeedback } from "../lib/ai.js";
import { createShareLink } from "../lib/share.js";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";

const server = new McpServer({
  name: "artifact-hub",
  version: "1.0.0",
});

// --- Tools ---

server.tool(
  "publish_artifact",
  "Publish a new artifact (HTML, text, markdown) to Artifact Hub. Tags and description are auto-generated by AI if not provided.",
  {
    title: z.string().describe("Title of the artifact"),
    content: z.string().describe("The artifact content (HTML, markdown, or plain text)"),
    mimeType: z
      .string()
      .default("text/html")
      .describe("MIME type of the content (text/html, text/markdown, text/plain)"),
    authorEmail: z.string().describe("Email of the author"),
    description: z.string().optional().describe("Optional description — AI will generate one if omitted"),
    tags: z.array(z.string()).optional().describe("Optional tags — AI will generate them if omitted"),
  },
  async ({ title, content, mimeType, authorEmail, description, tags }) => {
    const extMap: Record<string, string> = {
      "text/html": ".html",
      "text/markdown": ".md",
      "text/plain": ".txt",
    };
    const filename = `${title.replace(/[^a-zA-Z0-9-_]/g, "_").slice(0, 50)}${
      extMap[mimeType] || ""
    }`;

    const formData = new FormData();
    formData.append("file", new Blob([content], { type: mimeType }), filename);
    formData.append("title", title);
    formData.append("authorEmail", authorEmail);
    if (description) formData.append("description", description);
    if (tags && tags.length > 0) formData.append("tags", tags.join(","));

    const res = await fetch(`${BASE_URL}/api/artifacts`, {
      method: "POST",
      body: formData,
    });

    if (!res.ok) {
      const body = await res.text();
      return {
        content: [
          {
            type: "text" as const,
            text: `Publish failed (${res.status}): ${body}`,
          },
        ],
      };
    }

    const { artifact } = (await res.json()) as {
      artifact: {
        id: string;
        title: string;
        type: string;
        tags: string[];
        description: string | null;
      };
    };

    return {
      content: [
        {
          type: "text" as const,
          text: `Published "${artifact.title}" (${artifact.type})\nID: ${artifact.id}\nURL: ${BASE_URL}/artifacts/${artifact.id}\nTags: ${artifact.tags.join(", ")}\nDescription: ${artifact.description || "none"}`,
        },
      ],
    };
  }
);

server.tool(
  "search_artifacts",
  "Search artifacts by keyword in title/description, or filter by tag.",
  {
    query: z.string().optional().describe("Search text (matches title and description)"),
    tag: z.string().optional().describe("Filter by tag"),
    limit: z.number().default(10).describe("Max results"),
  },
  async ({ query, tag, limit }) => {
    const conditions = [];
    if (query) {
      conditions.push(
        or(ilike(artifacts.title, `%${query}%`), ilike(artifacts.description, `%${query}%`))
      );
    }
    if (tag) {
      conditions.push(sql`${tag} = ANY(${artifacts.tags})`);
    }

    const results = await db
      .select()
      .from(artifacts)
      .where(conditions.length > 0 ? conditions[0] : undefined)
      .orderBy(desc(artifacts.createdAt))
      .limit(limit);

    if (results.length === 0) {
      return { content: [{ type: "text" as const, text: "No artifacts found." }] };
    }

    const text = results
      .map(
        (a) =>
          `• ${a.title} (${a.type}) — ${a.tags.join(", ")}\n  ID: ${a.id}\n  ${a.description || ""}\n  URL: ${BASE_URL}/artifacts/${a.id}`
      )
      .join("\n\n");

    return { content: [{ type: "text" as const, text: `Found ${results.length} artifact(s):\n\n${text}` }] };
  }
);

server.tool(
  "get_artifact",
  "Get details of a specific artifact by ID.",
  {
    artifactId: z.string().describe("The artifact UUID"),
  },
  async ({ artifactId }) => {
    const [artifact] = await db
      .select()
      .from(artifacts)
      .where(eq(artifacts.id, artifactId))
      .limit(1);

    if (!artifact) {
      return { content: [{ type: "text" as const, text: "Artifact not found." }] };
    }

    return {
      content: [
        {
          type: "text" as const,
          text: `Title: ${artifact.title}\nType: ${artifact.type}\nAuthor: ${artifact.authorEmail}\nTags: ${artifact.tags.join(", ")}\nDescription: ${artifact.description || "none"}\nCreated: ${artifact.createdAt.toISOString()}\nFile: ${artifact.fileName} (${artifact.fileSize} bytes)\nURL: ${BASE_URL}/artifacts/${artifact.id}`,
        },
      ],
    };
  }
);

server.tool(
  "add_feedback",
  "Leave feedback/review on an artifact.",
  {
    artifactId: z.string().describe("The artifact UUID"),
    authorName: z.string().describe("Your name"),
    content: z.string().describe("Feedback content"),
    rating: z.number().min(1).max(5).optional().describe("Rating 1-5 (optional)"),
  },
  async ({ artifactId, authorName, content, rating }) => {
    const [item] = await db.insert(feedback).values({
      artifactId,
      authorName,
      content,
      rating: rating ?? null,
    }).returning();

    return {
      content: [
        {
          type: "text" as const,
          text: `Feedback added by ${item.authorName}${rating ? ` (${rating}/5)` : ""}: "${item.content}"`,
        },
      ],
    };
  }
);

server.tool(
  "summarize_feedback",
  "Get an AI-generated summary of all feedback on an artifact.",
  {
    artifactId: z.string().describe("The artifact UUID"),
  },
  async ({ artifactId }) => {
    const items = await db
      .select()
      .from(feedback)
      .where(eq(feedback.artifactId, artifactId));

    if (items.length === 0) {
      return { content: [{ type: "text" as const, text: "No feedback on this artifact yet." }] };
    }

    const summary = await summarizeFeedback(
      items.map((f) => ({ authorName: f.authorName, content: f.content, rating: f.rating }))
    );

    return {
      content: [
        {
          type: "text" as const,
          text: `Feedback summary (${items.length} reviews):\n\n${summary}`,
        },
      ],
    };
  }
);

server.tool(
  "create_share_link",
  "Create a time-limited share link for an artifact.",
  {
    artifactId: z.string().describe("The artifact UUID"),
    createdBy: z.string().describe("Your email or name"),
    expiresInHours: z.number().default(48).describe("Link validity in hours (default 48)"),
    maxViews: z.number().optional().describe("Max number of views (optional)"),
  },
  async ({ artifactId, createdBy, expiresInHours, maxViews }) => {
    const { token, expiresAt } = await createShareLink({
      artifactId,
      createdBy,
      expiresInHours,
      maxViews,
    });

    const shareUrl = `${BASE_URL}/share/${token}`;

    return {
      content: [
        {
          type: "text" as const,
          text: `Share link created: ${shareUrl}\nExpires: ${expiresAt.toISOString()}${maxViews ? `\nMax views: ${maxViews}` : ""}`,
        },
      ],
    };
  }
);

server.tool(
  "list_my_artifacts",
  "List artifacts published by a specific author.",
  {
    authorEmail: z.string().describe("Author email to filter by"),
    limit: z.number().default(20).describe("Max results"),
  },
  async ({ authorEmail, limit }) => {
    const results = await db
      .select()
      .from(artifacts)
      .where(eq(artifacts.authorEmail, authorEmail))
      .orderBy(desc(artifacts.createdAt))
      .limit(limit);

    if (results.length === 0) {
      return { content: [{ type: "text" as const, text: `No artifacts found for ${authorEmail}.` }] };
    }

    const text = results
      .map((a) => `• ${a.title} (${a.type}) — ${a.tags.join(", ")}\n  ID: ${a.id}`)
      .join("\n");

    return { content: [{ type: "text" as const, text: `${results.length} artifact(s) by ${authorEmail}:\n\n${text}` }] };
  }
);

// --- HTTP Server ---

const app = express();
app.use(cors());

app.post("/mcp", async (req, res) => {
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
  });
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
});

const PORT = parseInt(process.env.PORT || process.env.MCP_PORT || "3001");
app.listen(PORT, () => {
  console.log(`MCP server running on port ${PORT}`);
});
