import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
import cors from "cors";
import { z } from "zod";
import { db } from "../db/index.js";
import { artifacts, feedback } from "../db/schema.js";
import { and, eq, desc, ilike, or, sql } from "drizzle-orm";
import { summarizeFeedback } from "../lib/ai.js";
import { createShareLink } from "../lib/share.js";
import { resolveTokenToUser } from "../lib/tokens.js";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000";

interface BuildContext {
  ownerEmail: string;
  apiKey: string;
}

function buildMcpServer({ ownerEmail, apiKey }: BuildContext): McpServer {
  const server = new McpServer({
    name: "artifact-hub",
    version: "1.0.0",
  });

  server.tool(
    "publish_artifact",
    "Publish a new artifact (HTML, text, markdown) to Artifact Hub. Tags and description are auto-generated by AI if not provided. The artifact is owned by the account that owns this MCP token.",
    {
      title: z.string().describe("Title of the artifact"),
      content: z.string().describe("The artifact content (HTML, markdown, or plain text)"),
      mimeType: z
        .string()
        .default("text/html")
        .describe("MIME type of the content (text/html, text/markdown, text/plain)"),
      description: z.string().optional().describe("Optional description — AI will generate one if omitted"),
      tags: z.array(z.string()).optional().describe("Optional tags — AI will generate them if omitted"),
    },
    async ({ title, content, mimeType, description, tags }) => {
      const extMap: Record<string, string> = {
        "text/html": ".html",
        "text/markdown": ".md",
        "text/plain": ".txt",
      };
      const filename = `${title.replace(/[^a-zA-Z0-9-_]/g, "_").slice(0, 50)}${
        extMap[mimeType] || ""
      }`;

      const formData = new FormData();
      formData.append("file", new Blob([content], { type: mimeType }), filename);
      formData.append("title", title);
      if (description) formData.append("description", description);
      if (tags && tags.length > 0) formData.append("tags", tags.join(","));

      const res = await fetch(`${BASE_URL}/api/artifacts`, {
        method: "POST",
        headers: { "x-api-key": apiKey },
        body: formData,
      });

      if (!res.ok) {
        const body = await res.text();
        return {
          content: [
            {
              type: "text" as const,
              text: `Publish failed (${res.status}): ${body}`,
            },
          ],
        };
      }

      const { artifact } = (await res.json()) as {
        artifact: {
          id: string;
          title: string;
          type: string;
          tags: string[];
          description: string | null;
        };
      };

      return {
        content: [
          {
            type: "text" as const,
            text: `Published "${artifact.title}" (${artifact.type})\nID: ${artifact.id}\nURL: ${BASE_URL}/artifacts/${artifact.id}\nTags: ${artifact.tags.join(", ")}\nDescription: ${artifact.description || "none"}`,
          },
        ],
      };
    }
  );

  server.tool(
    "search_artifacts",
    "Search the caller's artifacts by keyword in title/description, or filter by tag. Only returns artifacts owned by the token holder.",
    {
      query: z.string().optional().describe("Search text (matches title and description)"),
      tag: z.string().optional().describe("Filter by tag"),
      limit: z.number().default(10).describe("Max results"),
    },
    async ({ query, tag, limit }) => {
      const conditions = [eq(artifacts.authorEmail, ownerEmail)];
      if (query) {
        const c = or(
          ilike(artifacts.title, `%${query}%`),
          ilike(artifacts.description, `%${query}%`)
        );
        if (c) conditions.push(c);
      }
      if (tag) {
        conditions.push(sql`${tag} = ANY(${artifacts.tags})`);
      }

      const results = await db
        .select()
        .from(artifacts)
        .where(and(...conditions))
        .orderBy(desc(artifacts.createdAt))
        .limit(limit);

      if (results.length === 0) {
        return { content: [{ type: "text" as const, text: "No artifacts found." }] };
      }

      const text = results
        .map(
          (a) =>
            `• ${a.title} (${a.type}) — ${a.tags.join(", ")}\n  ID: ${a.id}\n  ${a.description || ""}\n  URL: ${BASE_URL}/artifacts/${a.id}`
        )
        .join("\n\n");

      return { content: [{ type: "text" as const, text: `Found ${results.length} artifact(s):\n\n${text}` }] };
    }
  );

  server.tool(
    "get_artifact",
    "Get details of a specific artifact you own.",
    {
      artifactId: z.string().describe("The artifact UUID"),
    },
    async ({ artifactId }) => {
      const [artifact] = await db
        .select()
        .from(artifacts)
        .where(and(eq(artifacts.id, artifactId), eq(artifacts.authorEmail, ownerEmail)))
        .limit(1);

      if (!artifact) {
        return { content: [{ type: "text" as const, text: "Artifact not found." }] };
      }

      return {
        content: [
          {
            type: "text" as const,
            text: `Title: ${artifact.title}\nType: ${artifact.type}\nAuthor: ${artifact.authorEmail}\nTags: ${artifact.tags.join(", ")}\nDescription: ${artifact.description || "none"}\nCreated: ${artifact.createdAt.toISOString()}\nFile: ${artifact.fileName} (${artifact.fileSize} bytes)\nURL: ${BASE_URL}/artifacts/${artifact.id}`,
          },
        ],
      };
    }
  );

  server.tool(
    "add_feedback",
    "Leave feedback/review on one of your own artifacts.",
    {
      artifactId: z.string().describe("The artifact UUID"),
      authorName: z.string().describe("Display name to attach to this feedback"),
      content: z.string().describe("Feedback content"),
      rating: z.number().min(1).max(5).optional().describe("Rating 1-5 (optional)"),
    },
    async ({ artifactId, authorName, content, rating }) => {
      const [owned] = await db
        .select({ id: artifacts.id })
        .from(artifacts)
        .where(and(eq(artifacts.id, artifactId), eq(artifacts.authorEmail, ownerEmail)))
        .limit(1);
      if (!owned) {
        return { content: [{ type: "text" as const, text: "Artifact not found." }] };
      }

      const [item] = await db.insert(feedback).values({
        artifactId,
        authorName,
        content,
        rating: rating ?? null,
      }).returning();

      return {
        content: [
          {
            type: "text" as const,
            text: `Feedback added by ${item.authorName}${rating ? ` (${rating}/5)` : ""}: "${item.content}"`,
          },
        ],
      };
    }
  );

  server.tool(
    "summarize_feedback",
    "Get an AI-generated summary of all feedback on one of your artifacts.",
    {
      artifactId: z.string().describe("The artifact UUID"),
    },
    async ({ artifactId }) => {
      const [owned] = await db
        .select({ id: artifacts.id })
        .from(artifacts)
        .where(and(eq(artifacts.id, artifactId), eq(artifacts.authorEmail, ownerEmail)))
        .limit(1);
      if (!owned) {
        return { content: [{ type: "text" as const, text: "Artifact not found." }] };
      }

      const items = await db
        .select()
        .from(feedback)
        .where(eq(feedback.artifactId, artifactId));

      if (items.length === 0) {
        return { content: [{ type: "text" as const, text: "No feedback on this artifact yet." }] };
      }

      const summary = await summarizeFeedback(
        items.map((f) => ({ authorName: f.authorName, content: f.content, rating: f.rating }))
      );

      return {
        content: [
          {
            type: "text" as const,
            text: `Feedback summary (${items.length} reviews):\n\n${summary}`,
          },
        ],
      };
    }
  );

  server.tool(
    "create_share_link",
    "Create a time-limited share link for one of your artifacts.",
    {
      artifactId: z.string().describe("The artifact UUID"),
      expiresInHours: z.number().default(48).describe("Link validity in hours (default 48)"),
      maxViews: z.number().optional().describe("Max number of views (optional)"),
    },
    async ({ artifactId, expiresInHours, maxViews }) => {
      const [owned] = await db
        .select({ id: artifacts.id })
        .from(artifacts)
        .where(and(eq(artifacts.id, artifactId), eq(artifacts.authorEmail, ownerEmail)))
        .limit(1);
      if (!owned) {
        return { content: [{ type: "text" as const, text: "Artifact not found." }] };
      }

      const { token, expiresAt } = await createShareLink({
        artifactId,
        createdBy: ownerEmail,
        expiresInHours,
        maxViews,
      });

      const shareUrl = `${BASE_URL}/share/${token}`;

      return {
        content: [
          {
            type: "text" as const,
            text: `Share link created: ${shareUrl}\nExpires: ${expiresAt.toISOString()}${maxViews ? `\nMax views: ${maxViews}` : ""}`,
          },
        ],
      };
    }
  );

  server.tool(
    "list_my_artifacts",
    "List the artifacts you own.",
    {
      limit: z.number().default(20).describe("Max results"),
    },
    async ({ limit }) => {
      const results = await db
        .select()
        .from(artifacts)
        .where(eq(artifacts.authorEmail, ownerEmail))
        .orderBy(desc(artifacts.createdAt))
        .limit(limit);

      if (results.length === 0) {
        return { content: [{ type: "text" as const, text: "No artifacts yet." }] };
      }

      const text = results
        .map((a) => `• ${a.title} (${a.type}) — ${a.tags.join(", ")}\n  ID: ${a.id}`)
        .join("\n");

      return { content: [{ type: "text" as const, text: `${results.length} artifact(s):\n\n${text}` }] };
    }
  );

  return server;
}

// --- HTTP Server ---

const app = express();
app.use(cors());
app.use(express.json());

app.post("/mcp", async (req, res) => {
  const apiKey = (req.header("x-api-key") || "").trim();
  const resolved = apiKey ? await resolveTokenToUser(apiKey) : null;

  if (!resolved) {
    res.status(401).json({
      jsonrpc: "2.0",
      error: {
        code: -32001,
        message:
          "Missing or invalid x-api-key. Generate a token at " +
          `${BASE_URL}/settings/tokens and add it under "headers" in your MCP client config.`,
      },
      id: null,
    });
    return;
  }

  const server = buildMcpServer({ ownerEmail: resolved.userEmail, apiKey });
  const transport = new StreamableHTTPServerTransport({
    sessionIdGenerator: undefined,
  });

  res.on("close", () => {
    transport.close().catch(() => {});
    server.close().catch(() => {});
  });

  try {
    await server.connect(transport);
    await transport.handleRequest(req, res, req.body);
  } catch (err) {
    console.error("MCP request failed:", err);
    if (!res.headersSent) {
      res.status(500).json({
        jsonrpc: "2.0",
        error: { code: -32603, message: "Internal server error" },
        id: null,
      });
    }
  }
});

const PORT = parseInt(process.env.PORT || process.env.MCP_PORT || "3001");
app.listen(PORT, () => {
  console.log(`MCP server running on port ${PORT}`);
});
